//! Calibrated starting points for the target search.
//!
//! A seed table maps a SSIMULACRA2 target to the abstract quality at which
//! the median image of a calibration corpus first reaches it, with the
//! quartiles around that median. [`crate::Search`] starts at the seed and,
//! when the seed misses, steps by the corpus spread instead of bisecting the
//! whole range, so the first guess is usually within a step of the answer
//! (ADR-0001 D4).
//!
//! Tables are keyed by output format and backend tier, because the same
//! abstract quality means different things to different encoders. They are
//! calibrated at the default effort with automatic chroma subsampling; a
//! search at other settings still uses them, since a seed off by a few
//! steps costs an encode, not correctness.
//!
//! `tables.rs` is generated by `tools/calibrate` and never edited by hand.
//! The tool's README says how to regenerate it.

use sqzer_core::codec::{Format, Tier};

mod tables;

/// One calibrated point: at `target`, the median corpus image first reaches
/// the score at `quality`; `low` and `high` are the first and third
/// quartiles over the corpus.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SeedPoint {
    /// SSIMULACRA2 target.
    pub target: f32,
    /// Median quality that first reaches `target`.
    pub quality: f32,
    /// First quartile of that quality over the corpus.
    pub low: f32,
    /// Third quartile of that quality over the corpus.
    pub high: f32,
}

/// The calibration of one backend.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SeedTable {
    /// Output format.
    pub format: Format,
    /// Backend tier the table was calibrated on.
    pub tier: Tier,
    /// Backend crate and version the table was calibrated with.
    pub backend: &'static str,
    /// Corpus the table was calibrated on.
    pub corpus: &'static str,
    /// Images that went into the medians.
    pub images: u32,
    /// Points sorted by ascending target.
    pub points: &'static [SeedPoint],
}

/// Where a search should start for one target.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Seed {
    /// First quality to try.
    pub quality: f32,
    /// Distance of the second trial from the first when the first misses.
    pub step: f32,
}

/// Smallest and largest step a table hands out. The floor keeps a tight
/// corpus from creeping one quality at a time; the ceiling keeps a wild one
/// from jumping straight to the range end.
const STEP_RANGE: (f32, f32) = (2.0, 20.0);

/// Every committed table.
#[must_use]
pub fn tables() -> &'static [SeedTable] {
    tables::TABLES
}

/// The table for a backend, if one was calibrated.
#[must_use]
pub fn table(format: Format, tier: Tier) -> Option<&'static SeedTable> {
    tables::TABLES
        .iter()
        .find(|t| t.format == format && t.tier == tier)
}

/// Where to start a search for `target` on a backend, if it has a table.
#[must_use]
pub fn seed(format: Format, tier: Tier, target: f32) -> Option<Seed> {
    table(format, tier).map(|t| t.seed(target))
}

impl SeedTable {
    /// Where to start a search for `target`: the table interpolated
    /// linearly between its points and held flat beyond its ends.
    ///
    /// # Panics
    /// If the table has no points. Generated tables always have some.
    #[must_use]
    pub fn seed(&self, target: f32) -> Seed {
        let point = self.interpolate(target);
        let spread = (point.high - point.low).abs() / 2.0;
        Seed {
            quality: point.quality,
            step: spread.clamp(STEP_RANGE.0, STEP_RANGE.1),
        }
    }

    fn interpolate(&self, target: f32) -> SeedPoint {
        let points = self.points;
        assert!(!points.is_empty(), "a seed table must have points");
        let first = points[0];
        let last = points[points.len() - 1];
        if !target.is_finite() || target <= first.target {
            return first;
        }
        if target >= last.target {
            return last;
        }
        let i = points.partition_point(|p| p.target < target);
        let (a, b) = (points[i - 1], points[i]);
        let t = (target - a.target) / (b.target - a.target);
        let mix = |x: f32, y: f32| x + (y - x) * t;
        SeedPoint {
            target,
            quality: mix(a.quality, b.quality),
            low: mix(a.low, b.low),
            high: mix(a.high, b.high),
        }
    }
}

#[cfg(test)]
// Whole numbers and exact fractions: float equality is the intent.
#[allow(clippy::float_cmp)]
mod tests {
    use super::*;

    const POINTS: &[SeedPoint] = &[
        SeedPoint {
            target: 50.0,
            quality: 40.0,
            low: 30.0,
            high: 50.0,
        },
        SeedPoint {
            target: 70.0,
            quality: 60.0,
            low: 56.0,
            high: 64.0,
        },
        SeedPoint {
            target: 90.0,
            quality: 90.0,
            low: 89.0,
            high: 91.0,
        },
    ];

    const TABLE: SeedTable = SeedTable {
        format: Format::Jpeg,
        tier: Tier::Portable,
        backend: "test",
        corpus: "test",
        images: 3,
        points: POINTS,
    };

    #[test]
    fn interpolates_between_points_and_holds_the_ends() {
        assert_eq!(TABLE.seed(70.0).quality, 60.0);
        assert_eq!(TABLE.seed(60.0).quality, 50.0);
        assert_eq!(TABLE.seed(80.0).quality, 75.0);
        assert_eq!(TABLE.seed(0.0).quality, 40.0);
        assert_eq!(TABLE.seed(100.0).quality, 90.0);
        assert_eq!(TABLE.seed(f32::NAN).quality, 40.0);
    }

    #[test]
    fn step_is_half_the_spread_within_bounds() {
        assert_eq!(TABLE.seed(50.0).step, 10.0);
        assert_eq!(TABLE.seed(70.0).step, 4.0);
        // Half of 2 is below the floor.
        assert_eq!(TABLE.seed(90.0).step, STEP_RANGE.0);
        // Quartiles interpolate too: at 65 low is 49.5 and high 60.5.
        assert_eq!(TABLE.seed(65.0).step, 5.5);
    }

    #[test]
    fn committed_tables_are_well_formed() {
        for t in tables() {
            assert!(!t.points.is_empty(), "{}/{}: empty", t.format, t.tier);
            assert!(t.images > 0, "{}/{}: no images", t.format, t.tier);
            for w in t.points.windows(2) {
                assert!(
                    w[0].target < w[1].target,
                    "{}/{}: targets not ascending at {}",
                    t.format,
                    t.tier,
                    w[1].target
                );
                assert!(
                    w[0].quality <= w[1].quality,
                    "{}/{}: quality falls between targets {} and {}",
                    t.format,
                    t.tier,
                    w[0].target,
                    w[1].target
                );
            }
            for p in t.points {
                assert!(
                    (0.0..=100.0).contains(&p.quality)
                        && p.low <= p.quality
                        && p.quality <= p.high
                        && p.high <= 100.0,
                    "{}/{}: bad point {p:?}",
                    t.format,
                    t.tier
                );
            }
            // Each backend has one table.
            assert_eq!(
                tables()
                    .iter()
                    .filter(|o| o.format == t.format && o.tier == t.tier)
                    .count(),
                1
            );
        }
    }

    #[test]
    fn lookup_is_by_format_and_tier() {
        for t in tables() {
            assert_eq!(table(t.format, t.tier), Some(t));
            assert!(seed(t.format, t.tier, 70.0).is_some());
        }
        assert!(table(Format::Svg, Tier::Portable).is_none());
        assert!(seed(Format::Svg, Tier::Portable, 70.0).is_none());
    }
}
