// Generated by `tools/calibrate sweep` on 2026-09-11. Do not edit by hand;
// `tools/calibrate/README.md` says how to regenerate.
//
// Each point: at `target`, the median corpus image first reaches the
// score at `quality`; `low` and `high` are the quartiles. Calibrated at
// the default effort with automatic chroma subsampling, sources as
// sRGB with any ICC profile dropped.

use sqzer_core::codec::{Format, Tier};

use super::{SeedPoint, SeedTable};

#[rustfmt::skip]
pub(super) static TABLES: &[SeedTable] = &[
    // jpegli-sys 0.1.0+0.10.2: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    // Images that never reach the target at quality 100: 2 of 251 at 90, 147 of 251 at 95.
    SeedTable {
        format: Format::Jpeg,
        tier: Tier::Native,
        backend: "jpegli-sys 0.1.0+0.10.2",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 8.6, low: 5.5, high: 11.1 },
            SeedPoint { target: 25.0, quality: 10.5, low: 7.7, high: 13.3 },
            SeedPoint { target: 30.0, quality: 12.9, low: 10.2, high: 15.5 },
            SeedPoint { target: 35.0, quality: 15.1, low: 12.2, high: 17.9 },
            SeedPoint { target: 40.0, quality: 17.6, low: 14.6, high: 21.2 },
            SeedPoint { target: 45.0, quality: 21.0, low: 17.1, high: 25.3 },
            SeedPoint { target: 50.0, quality: 24.8, low: 20.7, high: 31.5 },
            SeedPoint { target: 55.0, quality: 32.7, low: 24.9, high: 44.3 },
            SeedPoint { target: 60.0, quality: 45.1, low: 34.0, high: 56.5 },
            SeedPoint { target: 65.0, quality: 57.8, low: 47.7, high: 66.4 },
            SeedPoint { target: 70.0, quality: 70.1, low: 62.2, high: 76.8 },
            SeedPoint { target: 75.0, quality: 80.8, low: 74.9, high: 85.4 },
            SeedPoint { target: 80.0, quality: 88.1, low: 84.7, high: 88.7 },
            SeedPoint { target: 85.0, quality: 89.7, low: 89.2, high: 90.1 },
            SeedPoint { target: 90.0, quality: 94.4, low: 93.5, high: 95.5 },
            SeedPoint { target: 95.0, quality: 99.4, low: 99.1, high: 99.7 },
        ],
    },
    // mozjpeg-rs 0.9.2: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    SeedTable {
        format: Format::Jpeg,
        tier: Tier::Portable,
        backend: "mozjpeg-rs 0.9.2",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 16.9, low: 14.3, high: 19.0 },
            SeedPoint { target: 25.0, quality: 18.5, low: 15.9, high: 21.1 },
            SeedPoint { target: 30.0, quality: 20.6, low: 17.6, high: 23.1 },
            SeedPoint { target: 35.0, quality: 23.1, low: 19.8, high: 26.1 },
            SeedPoint { target: 40.0, quality: 25.9, low: 22.2, high: 29.5 },
            SeedPoint { target: 45.0, quality: 29.7, low: 25.3, high: 33.7 },
            SeedPoint { target: 50.0, quality: 33.9, low: 28.9, high: 39.1 },
            SeedPoint { target: 55.0, quality: 40.1, low: 33.6, high: 45.4 },
            SeedPoint { target: 60.0, quality: 48.5, low: 40.8, high: 55.9 },
            SeedPoint { target: 65.0, quality: 59.2, low: 49.9, high: 65.4 },
            SeedPoint { target: 70.0, quality: 69.0, low: 62.1, high: 73.6 },
            SeedPoint { target: 75.0, quality: 77.9, low: 72.5, high: 82.5 },
            SeedPoint { target: 80.0, quality: 86.0, low: 82.7, high: 88.4 },
            SeedPoint { target: 85.0, quality: 89.6, low: 88.9, high: 90.1 },
            SeedPoint { target: 90.0, quality: 94.8, low: 93.9, high: 95.7 },
            SeedPoint { target: 95.0, quality: 99.5, low: 99.3, high: 99.8 },
        ],
    },
    // webpx 0.4.0 + libwebp-sys 0.14.4: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    // Images that never reach the target at quality 100: 2 of 251 at 70, 6 of 251 at 75, 16 of 251 at 80, 48 of 251 at 85, 209 of 251 at 90, 250 of 251 at 95.
    SeedTable {
        format: Format::WebP,
        tier: Tier::Native,
        backend: "webpx 0.4.0 + libwebp-sys 0.14.4",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 3.2, low: 2.0, high: 7.3 },
            SeedPoint { target: 25.0, quality: 5.1, low: 2.1, high: 10.4 },
            SeedPoint { target: 30.0, quality: 7.6, low: 3.6, high: 13.8 },
            SeedPoint { target: 35.0, quality: 10.9, low: 5.9, high: 17.8 },
            SeedPoint { target: 40.0, quality: 14.9, low: 9.6, high: 22.7 },
            SeedPoint { target: 45.0, quality: 19.9, low: 13.8, high: 28.2 },
            SeedPoint { target: 50.0, quality: 26.1, low: 19.6, high: 34.2 },
            SeedPoint { target: 55.0, quality: 33.7, low: 26.4, high: 43.0 },
            SeedPoint { target: 60.0, quality: 42.6, low: 34.8, high: 53.9 },
            SeedPoint { target: 65.0, quality: 55.8, low: 45.5, high: 66.1 },
            SeedPoint { target: 70.0, quality: 69.8, low: 61.2, high: 76.8 },
            SeedPoint { target: 75.0, quality: 78.9, low: 76.3, high: 82.0 },
            SeedPoint { target: 80.0, quality: 85.3, low: 83.4, high: 87.7 },
            SeedPoint { target: 85.0, quality: 91.6, low: 89.8, high: 93.7 },
            SeedPoint { target: 90.0, quality: 95.8, low: 95.0, high: 97.4 },
            SeedPoint { target: 95.0, quality: 100.0, low: 100.0, high: 100.0 },
        ],
    },
    // libavif-sys 0.17.0+libavif.1.0.4 + libaom-sys 0.17.2+libaom.3.11.0: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    // Images that never reach the target at quality 100: 8 of 251 at 90, 240 of 251 at 95.
    SeedTable {
        format: Format::Avif,
        tier: Tier::Native,
        backend: "libavif-sys 0.17.0+libavif.1.0.4 + libaom-sys 0.17.2+libaom.3.11.0",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 17.2, low: 13.1, high: 20.6 },
            SeedPoint { target: 25.0, quality: 19.0, low: 15.2, high: 23.1 },
            SeedPoint { target: 30.0, quality: 21.4, low: 17.4, high: 25.7 },
            SeedPoint { target: 35.0, quality: 24.2, low: 19.5, high: 28.8 },
            SeedPoint { target: 40.0, quality: 27.2, low: 22.5, high: 31.9 },
            SeedPoint { target: 45.0, quality: 30.5, low: 25.8, high: 35.2 },
            SeedPoint { target: 50.0, quality: 34.4, low: 29.5, high: 38.4 },
            SeedPoint { target: 55.0, quality: 38.2, low: 33.8, high: 41.9 },
            SeedPoint { target: 60.0, quality: 42.1, low: 38.2, high: 45.9 },
            SeedPoint { target: 65.0, quality: 46.9, low: 43.0, high: 50.4 },
            SeedPoint { target: 70.0, quality: 52.1, low: 49.0, high: 54.9 },
            SeedPoint { target: 75.0, quality: 58.1, low: 54.7, high: 62.5 },
            SeedPoint { target: 80.0, quality: 68.9, low: 64.4, high: 74.1 },
            SeedPoint { target: 85.0, quality: 83.4, low: 80.6, high: 85.9 },
            SeedPoint { target: 90.0, quality: 89.4, low: 88.4, high: 91.8 },
            SeedPoint { target: 95.0, quality: 98.5, low: 96.3, high: 99.6 },
        ],
    },
    // ravif 0.13.0 + rav1e 0.8.1: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    SeedTable {
        format: Format::Avif,
        tier: Tier::Portable,
        backend: "ravif 0.13.0 + rav1e 0.8.1",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 17.8, low: 13.8, high: 21.9 },
            SeedPoint { target: 25.0, quality: 19.7, low: 15.7, high: 23.7 },
            SeedPoint { target: 30.0, quality: 21.8, low: 17.8, high: 26.7 },
            SeedPoint { target: 35.0, quality: 24.0, low: 20.1, high: 31.1 },
            SeedPoint { target: 40.0, quality: 27.6, low: 22.4, high: 35.7 },
            SeedPoint { target: 45.0, quality: 32.9, low: 25.0, high: 39.9 },
            SeedPoint { target: 50.0, quality: 38.2, low: 30.4, high: 45.6 },
            SeedPoint { target: 55.0, quality: 44.0, low: 36.9, high: 50.6 },
            SeedPoint { target: 60.0, quality: 50.3, low: 43.4, high: 57.2 },
            SeedPoint { target: 65.0, quality: 58.5, low: 51.0, high: 64.2 },
            SeedPoint { target: 70.0, quality: 66.4, low: 59.9, high: 73.0 },
            SeedPoint { target: 75.0, quality: 77.3, low: 70.3, high: 80.7 },
            SeedPoint { target: 80.0, quality: 83.1, low: 81.3, high: 84.5 },
            SeedPoint { target: 85.0, quality: 87.8, low: 86.6, high: 88.6 },
            SeedPoint { target: 90.0, quality: 92.6, low: 92.0, high: 93.1 },
            SeedPoint { target: 95.0, quality: 98.1, low: 97.6, high: 98.7 },
        ],
    },
    // gamut-jxl 0.4.0 + jpegxl-src 0.12.0: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    // Images that never reach the target at quality 100: 35 of 251 at 95.
    SeedTable {
        format: Format::Jxl,
        tier: Tier::Native,
        backend: "gamut-jxl 0.4.0 + jpegxl-src 0.12.0",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 8.6, low: 5.0, high: 15.1 },
            SeedPoint { target: 25.0, quality: 11.5, low: 5.0, high: 16.5 },
            SeedPoint { target: 30.0, quality: 14.7, low: 7.4, high: 18.0 },
            SeedPoint { target: 35.0, quality: 16.4, low: 11.2, high: 20.2 },
            SeedPoint { target: 40.0, quality: 18.2, low: 14.5, high: 23.1 },
            SeedPoint { target: 45.0, quality: 20.6, low: 16.9, high: 26.8 },
            SeedPoint { target: 50.0, quality: 24.1, low: 18.8, high: 35.8 },
            SeedPoint { target: 55.0, quality: 29.5, low: 22.0, high: 46.0 },
            SeedPoint { target: 60.0, quality: 42.7, low: 26.4, high: 55.7 },
            SeedPoint { target: 65.0, quality: 53.5, low: 38.9, high: 63.4 },
            SeedPoint { target: 70.0, quality: 63.0, low: 52.3, high: 70.2 },
            SeedPoint { target: 75.0, quality: 71.9, low: 64.4, high: 77.4 },
            SeedPoint { target: 80.0, quality: 80.5, low: 75.4, high: 83.9 },
            SeedPoint { target: 85.0, quality: 87.5, low: 84.4, high: 89.8 },
            SeedPoint { target: 90.0, quality: 93.6, low: 92.2, high: 95.0 },
            SeedPoint { target: 95.0, quality: 98.7, low: 98.3, high: 99.0 },
        ],
    },
];
