// Generated by `tools/calibrate sweep` on 2026-09-07. Do not edit by hand;
// `tools/calibrate/README.md` says how to regenerate.
//
// Each point: at `target`, the median corpus image first reaches the
// score at `quality`; `low` and `high` are the quartiles. Calibrated at
// the default effort with automatic chroma subsampling, sources as
// sRGB with any ICC profile dropped.

use sqzer_core::codec::{Format, Tier};

use super::{SeedPoint, SeedTable};

#[rustfmt::skip]
pub(super) static TABLES: &[SeedTable] = &[
    // mozjpeg-rs 0.9.2: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    // Images that never reach the target at quality 100: 2 of 251 at 90, 126 of 251 at 95.
    SeedTable {
        format: Format::Jpeg,
        tier: Tier::Portable,
        backend: "mozjpeg-rs 0.9.2",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 16.9, low: 14.3, high: 19.0 },
            SeedPoint { target: 25.0, quality: 18.5, low: 15.9, high: 21.1 },
            SeedPoint { target: 30.0, quality: 20.6, low: 17.6, high: 23.1 },
            SeedPoint { target: 35.0, quality: 23.1, low: 19.8, high: 26.1 },
            SeedPoint { target: 40.0, quality: 25.9, low: 22.2, high: 29.5 },
            SeedPoint { target: 45.0, quality: 29.7, low: 25.3, high: 33.7 },
            SeedPoint { target: 50.0, quality: 33.9, low: 28.9, high: 39.1 },
            SeedPoint { target: 55.0, quality: 40.1, low: 33.6, high: 45.4 },
            SeedPoint { target: 60.0, quality: 48.5, low: 40.8, high: 55.9 },
            SeedPoint { target: 65.0, quality: 59.2, low: 49.9, high: 65.4 },
            SeedPoint { target: 70.0, quality: 69.0, low: 62.1, high: 73.6 },
            SeedPoint { target: 75.0, quality: 77.9, low: 72.5, high: 82.5 },
            SeedPoint { target: 80.0, quality: 86.0, low: 82.7, high: 88.4 },
            SeedPoint { target: 85.0, quality: 89.6, low: 88.9, high: 90.1 },
            SeedPoint { target: 90.0, quality: 94.8, low: 93.9, high: 95.7 },
            SeedPoint { target: 95.0, quality: 99.5, low: 99.3, high: 99.8 },
        ],
    },
    // libwebp-sys 0.9.6: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    // Images that never reach the target at quality 100: 2 of 251 at 70, 6 of 251 at 75, 16 of 251 at 80, 48 of 251 at 85, 209 of 251 at 90, 250 of 251 at 95.
    SeedTable {
        format: Format::WebP,
        tier: Tier::Native,
        backend: "libwebp-sys 0.9.6",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 3.2, low: 2.0, high: 7.3 },
            SeedPoint { target: 25.0, quality: 5.1, low: 2.1, high: 10.4 },
            SeedPoint { target: 30.0, quality: 7.6, low: 3.6, high: 13.8 },
            SeedPoint { target: 35.0, quality: 10.9, low: 5.9, high: 17.8 },
            SeedPoint { target: 40.0, quality: 14.9, low: 9.6, high: 22.7 },
            SeedPoint { target: 45.0, quality: 19.9, low: 13.8, high: 28.2 },
            SeedPoint { target: 50.0, quality: 26.1, low: 19.6, high: 34.2 },
            SeedPoint { target: 55.0, quality: 33.7, low: 26.4, high: 43.0 },
            SeedPoint { target: 60.0, quality: 42.6, low: 34.8, high: 53.9 },
            SeedPoint { target: 65.0, quality: 55.8, low: 45.5, high: 66.1 },
            SeedPoint { target: 70.0, quality: 69.8, low: 61.2, high: 76.8 },
            SeedPoint { target: 75.0, quality: 78.9, low: 76.3, high: 82.0 },
            SeedPoint { target: 80.0, quality: 85.3, low: 83.4, high: 87.7 },
            SeedPoint { target: 85.0, quality: 91.6, low: 89.8, high: 93.7 },
            SeedPoint { target: 90.0, quality: 95.8, low: 95.0, high: 97.4 },
            SeedPoint { target: 95.0, quality: 100.0, low: 100.0, high: 100.0 },
        ],
    },
    // ravif 0.13.0 + rav1e 0.8.1: CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)
    // Images that never reach the target at quality 100: 1 of 251 at 90, 61 of 251 at 95.
    SeedTable {
        format: Format::Avif,
        tier: Tier::Portable,
        backend: "ravif 0.13.0 + rav1e 0.8.1",
        corpus: "CID22/CID22-512/training (209), clic2025/training (32), gb82-sc (10)",
        images: 251,
        points: &[
            SeedPoint { target: 20.0, quality: 17.8, low: 13.8, high: 21.9 },
            SeedPoint { target: 25.0, quality: 19.7, low: 15.7, high: 23.7 },
            SeedPoint { target: 30.0, quality: 21.8, low: 17.8, high: 26.7 },
            SeedPoint { target: 35.0, quality: 24.0, low: 20.1, high: 31.1 },
            SeedPoint { target: 40.0, quality: 27.6, low: 22.4, high: 35.7 },
            SeedPoint { target: 45.0, quality: 32.9, low: 25.0, high: 39.9 },
            SeedPoint { target: 50.0, quality: 38.2, low: 30.4, high: 45.6 },
            SeedPoint { target: 55.0, quality: 44.0, low: 36.9, high: 50.6 },
            SeedPoint { target: 60.0, quality: 50.3, low: 43.4, high: 57.2 },
            SeedPoint { target: 65.0, quality: 58.5, low: 51.0, high: 64.2 },
            SeedPoint { target: 70.0, quality: 66.4, low: 59.9, high: 73.0 },
            SeedPoint { target: 75.0, quality: 77.3, low: 70.3, high: 80.7 },
            SeedPoint { target: 80.0, quality: 83.1, low: 81.3, high: 84.5 },
            SeedPoint { target: 85.0, quality: 87.8, low: 86.6, high: 88.6 },
            SeedPoint { target: 90.0, quality: 92.6, low: 92.0, high: 93.1 },
            SeedPoint { target: 95.0, quality: 98.1, low: 97.6, high: 98.7 },
        ],
    },
];
