[package]
name = "sqzer-cli"
description = "Command-line interface for sqzer."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "sqzer"
path = "src/main.rs"
doc = false

[features]
default = ["portable"]
portable = ["sqzer/portable"]
native = ["sqzer/native"]

[dependencies]
sqzer.workspace = true

[lints]
workspace = true
